### ISSUE TITLE
Asus C201p Mouse Only Left-Click

### ISSUE THREAD

**Issue by Wooty-B** [SolidHal/PrawnOS#306] opened 2022-09-18 13:53 UTC
Touch-pad is only registering left-clicks, and can't seem to enable the right mouse button. Not sure if this is a "feature" of PrawnOS but if it is there is no information on the right-click modifier key.

How do I enable the right mouse button?

**Comment by cracket** [comment] 2022-10-01 14:24
duplicate of #286 ?

**Comment by Wooty-B** [comment] 2022-10-05 04:51
@cracket This is in-fact a duplicate, and I was able to resolve with steps in that thread. Closing, however may be useful to add to C201p install config in the future.

**Closed** 2022-10-21 19:56 UTC
Labels: bug
